const fs = require('fs');
const path = require('path');

const originalItems = [
  {
    id: 'g1',
    name: 'Basmati Rice (5 kg)',
    category: 'Staples',
    price: 320,
    mrp: 380,
    unit: '5 kg',
    image: 'https://www.organicgyaan.com/cdn/shop/files/Basmati-Rice.jpg?v=1721449479&width=1214',
    inStock: true,
    bulkSaving: 60,
    pooledOrders: 14,
  },
  {
    id: 'g2',
    name: 'Toor Dal (1 kg)',
    category: 'Staples',
    price: 130,
    mrp: 155,
    unit: '1 kg',
    image: 'https://cdn.shopaccino.com/edible-smart/products/toor-dal-min-scaled-740285_l.jpg?v=704',
    inStock: true,
    bulkSaving: 25,
    pooledOrders: 22,
  },
  {
    id: 'g3',
    name: 'Amul Full Cream Milk (1 L)',
    category: 'Dairy',
    price: 68,
    mrp: 72,
    unit: '1 L',
    image: 'https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/NI_CATALOG/IMAGES/ciw/2025/12/17/51a2cd89-2a42-4b2b-ac97-95288e02952d_TYF3262KU8_MN_16122025.png',
    inStock: true,
    bulkSaving: 4,
    pooledOrders: 31,
  },
  {
    id: 'g4',
    name: 'Lay\'s Chips Variety Pack (6 pcs)',
    category: 'Snacks',
    price: 120,
    mrp: 150,
    unit: '6 pcs',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQH1753hvAhqfCWAZr-FdmLSDUtMT3HS68unw&s',
    inStock: true,
    bulkSaving: 30,
    pooledOrders: 18,
  },
  {
    id: 'g5',
    name: 'Banana (12 pcs)',
    category: 'Fruits & Veggies',
    price: 48,
    mrp: 60,
    unit: '12 pcs',
    image: 'https://d10i8ghbmk7qrh.cloudfront.net/images/product/68bc01f07fea31757151729.webp',
    inStock: true,
    bulkSaving: 12,
    pooledOrders: 27,
  },
  {
    id: 'g6',
    name: 'Maggi Noodles (6 pack)',
    category: 'Instant Food',
    price: 156,
    mrp: 192,
    unit: '12 × 70g',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRht0SAIH83GNYcUEAWb8W3z7Re_5MHYfPmDQ&s',
    inStock: true,
    bulkSaving: 36,
    pooledOrders: 45,
  },
  {
    id: 'g7',
    name: 'Sunflower Oil (1 L)',
    category: 'Staples',
    price: 145,
    mrp: 165,
    unit: '1 L',
    image: 'https://www.quickpantry.in/cdn/shop/products/fortune-sunflower-refined-oil-1-l-quick-pantry.jpg?v=1710538009',
    inStock: true,
    bulkSaving: 20,
    pooledOrders: 12,
  },
  {
    id: 'g8',
    name: 'Amul Butter (500g)',
    category: 'Dairy',
    price: 250,
    mrp: 280,
    unit: '500 g',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3oL49SGhvPJjJVfU9srkMRI8vtsk4FmnPTw&s',
    inStock: true,
    bulkSaving: 30,
    pooledOrders: 20,
  },
  {
    id: 'g9',
    name: 'Bru Coffee (200g)',
    category: 'Beverages',
    price: 185,
    mrp: 210,
    unit: '200 g',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLhPWQD2xGCBDNul10q3D22nGZCaT7wuK9lg&s',
    inStock: true,
    bulkSaving: 25,
    pooledOrders: 19,
  },
  {
    id: 'g10',
    name: 'Tomatoes (1 kg)',
    category: 'Fruits & Veggies',
    price: 40,
    mrp: 55,
    unit: '1 kg',
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=300&q=80',
    inStock: true,
    bulkSaving: 15,
    pooledOrders: 33,
  },
  {
    id: 'g11',
    name: 'Britannia Biscuits (10 pack)',
    category: 'Snacks',
    price: 90,
    mrp: 110,
    unit: '10 × 100g',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=300&q=80',
    inStock: true,
    bulkSaving: 20,
    pooledOrders: 28,
  },
  {
    id: 'g12',
    name: 'Dove Shampoo (180ml)',
    category: 'Personal Care',
    price: 160,
    mrp: 190,
    unit: '180 ml',
    image: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/1013794/HOsqIhHfy2-1013794_1.jpg',
    inStock: false,
    bulkSaving: 30,
    pooledOrders: 8,
  },
  {
    id: 'g13',
    name: 'Mtr Ready Meals (Paneer)',
    category: 'Instant Food',
    price: 85,
    mrp: 99,
    unit: '300 g',
    image: 'https://thedesifood.com/media/MTR%20Ready%20To%20Eat%20-%20Shahi%20Paneer,%20300%20g%20Carton-1.webp',
    inStock: true,
    bulkSaving: 14,
    pooledOrders: 17,
  },
  {
    id: 'g14',
    name: 'Heritaage Curd (400g)',
    category: 'Dairy',
    price: 40,
    mrp: 48,
    unit: '400 g',
    image: 'https://m.media-amazon.com/images/I/71suj8wGr1L.jpg',
    inStock: true,
    bulkSaving: 8,
    pooledOrders: 25,
  },
  {
    id: 'g15',
    name: 'Aashirvaad Atta (5 kg)',
    category: 'Staples',
    price: 255,
    mrp: 300,
    unit: '5 kg',
    image: 'https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/NI_CATALOG/IMAGES/ciw/2025/12/16/4acaf178-2e67-4bd3-9cb8-6ca62686b956_ATSS4643F5_MN_16122025.png',
    inStock: true,
    bulkSaving: 45,
    pooledOrders: 21,
  },
  {
    id: 'g16',
    name: 'Coca-Cola',
    category: 'Beverages',
    price: 55,
    mrp: 65,
    unit: '1 L',
    image: 'https://cdn.pixabay.com/photo/2019/03/29/20/36/coca-cola-4090021_1280.jpg',
    inStock: true,
    bulkSaving: 10,
    pooledOrders: 36,
  },
  {
    id: 'g17',
    name: 'Onions (2 kg)',
    category: 'Fruits & Veggies',
    price: 50,
    mrp: 65,
    unit: '2 kg',
    image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=300&q=80',
    inStock: true,
    bulkSaving: 15,
    pooledOrders: 30,
  },
  {
    id: 'g18',
    name: 'Good Day Cashew Cookies',
    category: 'Snacks',
    price: 30,
    mrp: 35,
    unit: '150 g',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7ksi9SrHClzvnEbLR7cIx9QXhY90xcyv3mQ&s',
    inStock: true,
    bulkSaving: 5,
    pooledOrders: 42,
  },
  {
    id: 'g19',
    name: 'Dettol Hand Wash (250ml)',
    category: 'Personal Care',
    price: 85,
    mrp: 99,
    unit: '250 ml',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSG6iqLXTXaZfnf52rnN_xPwgob3HlsERX6wg&s',
    inStock: true,
    bulkSaving: 14,
    pooledOrders: 15,
  },
  {
    id: 'g20',
    name: 'Poha (500g)',
    category: 'Staples',
    price: 35,
    mrp: 42,
    unit: '500 g',
    image: 'https://www.patanjaliayurved.net/assets/product_images/400x500/1690278984poha500g1.png',
    inStock: true,
    bulkSaving: 7,
    pooledOrders: 11,
  },
];

const newItemsData = [
  // STAPLES
  { name: 'Moong Dal (1 kg)', category: 'Staples', price: 120, mrp: 140, unit: '1 kg', brand: 'Tata Sampann', discount: 14, deliveryTime: '10-20 mins' },
  { name: 'Sugar (1 kg)', category: 'Staples', price: 45, mrp: 55, unit: '1 kg', brand: 'Madhur', discount: 18, deliveryTime: '10-20 mins' },
  { name: 'Tata Salt (1 kg)', category: 'Staples', price: 24, mrp: 28, unit: '1 kg', brand: 'Tata', discount: 14, deliveryTime: '10-20 mins' },
  { name: 'Fortune Soya Health Oil (1 L)', category: 'Staples', price: 135, mrp: 155, unit: '1 L', brand: 'Fortune', discount: 12, deliveryTime: '20-30 mins' },
  { name: 'Rajdhani Sooji/Suji (500g)', category: 'Staples', price: 30, mrp: 35, unit: '500 g', brand: 'Rajdhani', discount: 14, deliveryTime: '10-20 mins' },
  { name: 'Rajdhani Besan (500g)', category: 'Staples', price: 45, mrp: 55, unit: '500 g', brand: 'Rajdhani', discount: 18, deliveryTime: '10-20 mins' },
  { name: 'Bambino Roasted Vermicelli (500g)', category: 'Staples', price: 65, mrp: 75, unit: '500 g', brand: 'Bambino', discount: 13, deliveryTime: '10-20 mins' },
  { name: 'Quaker Oats (1 kg)', category: 'Staples', price: 180, mrp: 199, unit: '1 kg', brand: 'Quaker', discount: 9, deliveryTime: '20-30 mins' },
  { name: 'Pintola Peanut Butter Crunchy (350g)', category: 'Staples', price: 140, mrp: 165, unit: '350 g', brand: 'Pintola', discount: 15, deliveryTime: '20-30 mins' },
  { name: 'Happilo Premium Almonds (200g)', category: 'Staples', price: 280, mrp: 350, unit: '200 g', brand: 'Happilo', discount: 20, deliveryTime: '20-30 mins' },

  // SNACKS
  { name: 'Doritos Nacho Cheese (60g)', category: 'Snacks', price: 30, mrp: 30, unit: '60 g', brand: 'Doritos', discount: 0, deliveryTime: '10-20 mins' },
  { name: 'Act II Butter Popcorn (150g)', category: 'Snacks', price: 60, mrp: 65, unit: '150 g', brand: 'Act II', discount: 7, deliveryTime: '10-20 mins' },
  { name: 'Cadbury Dairy Milk Silk (150g)', category: 'Snacks', price: 160, mrp: 175, unit: '150 g', brand: 'Cadbury', discount: 8, deliveryTime: '10-20 mins' },
  { name: 'Sunfeast Dark Fantasy Choco Fills (75g)', category: 'Snacks', price: 40, mrp: 45, unit: '75 g', brand: 'Sunfeast', discount: 11, deliveryTime: '10-20 mins' },
  { name: 'RiteBite Max Protein Bar (50g)', category: 'Snacks', price: 65, mrp: 75, unit: '50 g', brand: 'RiteBite', discount: 13, deliveryTime: '10-20 mins' },
  { name: 'Haldiram\'s Khatta Meetha (200g)', category: 'Snacks', price: 50, mrp: 55, unit: '200 g', brand: 'Haldiram\'s', discount: 9, deliveryTime: '10-20 mins' },
  { name: 'A1 Mini Murukku (150g)', category: 'Snacks', price: 45, mrp: 50, unit: '150 g', brand: 'A1', discount: 10, deliveryTime: '10-20 mins' },
  { name: 'Britannia Cake - Chocolate (40g)', category: 'Snacks', price: 15, mrp: 15, unit: '40 g', brand: 'Britannia', discount: 0, deliveryTime: '10-20 mins' },
  { name: 'Beyond Snack Kerala Banana Chips (85g)', category: 'Snacks', price: 60, mrp: 70, unit: '85 g', brand: 'Beyond Snack', discount: 14, deliveryTime: '10-20 mins' },
  { name: 'Pringles Original (107g)', category: 'Snacks', price: 105, mrp: 115, unit: '107 g', brand: 'Pringles', discount: 8, deliveryTime: '10-20 mins' },

  // DAIRY
  { name: 'Amul Cheese Slices (200g)', category: 'Dairy', price: 125, mrp: 135, unit: '200 g', brand: 'Amul', discount: 7, deliveryTime: '10-20 mins' },
  { name: 'Milky Mist Paneer (200g)', category: 'Dairy', price: 85, mrp: 95, unit: '200 g', brand: 'Milky Mist', discount: 10, deliveryTime: '10-20 mins' },
  { name: 'Epigamia Greek Yogurt (120g)', category: 'Dairy', price: 70, mrp: 75, unit: '120 g', brand: 'Epigamia', discount: 6, deliveryTime: '10-20 mins' },
  { name: 'Amul Ice Cream Tub (1L)', category: 'Dairy', price: 190, mrp: 220, unit: '1 L', brand: 'Amul', discount: 13, deliveryTime: '10-20 mins' },
  { name: 'Gowardhan Ghee (1L)', category: 'Dairy', price: 590, mrp: 650, unit: '1 L', brand: 'Gowardhan', discount: 9, deliveryTime: '20-30 mins' },
  { name: 'Amul Fresh Cream (250ml)', category: 'Dairy', price: 65, mrp: 70, unit: '250 ml', brand: 'Amul', discount: 7, deliveryTime: '10-20 mins' },
  { name: 'Mother Dairy Buttermilk (400ml)', category: 'Dairy', price: 20, mrp: 22, unit: '400 ml', brand: 'Mother Dairy', discount: 9, deliveryTime: '10-20 mins' },
  { name: 'Nandini Good Life Milk (500ml)', category: 'Dairy', price: 26, mrp: 28, unit: '500 ml', brand: 'Nandini', discount: 7, deliveryTime: '10-20 mins' },
  { name: 'Britannia Cheese Cubes (200g)', category: 'Dairy', price: 120, mrp: 130, unit: '200 g', brand: 'Britannia', discount: 7, deliveryTime: '10-20 mins' },
  { name: 'Amul Taaza Milk (1L)', category: 'Dairy', price: 62, mrp: 64, unit: '1 L', brand: 'Amul', discount: 3, deliveryTime: '10-20 mins' },

  // FRUITS & VEGGIES
  { name: 'Kashmir Apples (1 kg)', category: 'Fruits & Veggies', price: 150, mrp: 180, unit: '1 kg', brand: 'Fresh', discount: 16, deliveryTime: '10-20 mins' },
  { name: 'Nagpur Oranges (1 kg)', category: 'Fruits & Veggies', price: 80, mrp: 100, unit: '1 kg', brand: 'Fresh', discount: 20, deliveryTime: '10-20 mins' },
  { name: 'Alphonso Mangoes (6 pcs)', category: 'Fruits & Veggies', price: 450, mrp: 500, unit: '6 pcs', brand: 'Fresh', discount: 10, deliveryTime: '10-20 mins' },
  { name: 'Potatoes (2 kg)', category: 'Fruits & Veggies', price: 60, mrp: 80, unit: '2 kg', brand: 'Fresh', discount: 25, deliveryTime: '10-20 mins' },
  { name: 'Carrots (500g)', category: 'Fruits & Veggies', price: 30, mrp: 40, unit: '500 g', brand: 'Fresh', discount: 25, deliveryTime: '10-20 mins' },
  { name: 'Fresh Spinach (1 bunch)', category: 'Fruits & Veggies', price: 20, mrp: 25, unit: '1 bunch', brand: 'Fresh', discount: 20, deliveryTime: '10-20 mins' },
  { name: 'Green Capsicum (500g)', category: 'Fruits & Veggies', price: 40, mrp: 55, unit: '500 g', brand: 'Fresh', discount: 27, deliveryTime: '10-20 mins' },
  { name: 'Cucumber (1 kg)', category: 'Fruits & Veggies', price: 45, mrp: 60, unit: '1 kg', brand: 'Fresh', discount: 25, deliveryTime: '10-20 mins' },
  { name: 'Watermelon (1 pc)', category: 'Fruits & Veggies', price: 80, mrp: 100, unit: '1 pc', brand: 'Fresh', discount: 20, deliveryTime: '10-20 mins' },
  { name: 'Pomegranate (4 pcs)', category: 'Fruits & Veggies', price: 120, mrp: 150, unit: '4 pcs', brand: 'Fresh', discount: 20, deliveryTime: '10-20 mins' },

  // INSTANT FOOD
  { name: 'Nissin Cup Noodles (70g)', category: 'Instant Food', price: 45, mrp: 50, unit: '70 g', brand: 'Nissin', discount: 10, deliveryTime: '10-20 mins' },
  { name: 'Sunfeast Yippee Noodles (240g)', category: 'Instant Food', price: 55, mrp: 60, unit: '240 g', brand: 'Sunfeast', discount: 8, deliveryTime: '10-20 mins' },
  { name: 'McCain French Fries (400g)', category: 'Instant Food', price: 140, mrp: 160, unit: '400 g', brand: 'McCain', discount: 12, deliveryTime: '20-30 mins' },
  { name: 'Prasuma Chicken Momos (250g)', category: 'Instant Food', price: 180, mrp: 200, unit: '250 g', brand: 'Prasuma', discount: 10, deliveryTime: '20-30 mins' },
  { name: 'Knorr Sweet Corn Soup (44g)', category: 'Instant Food', price: 55, mrp: 60, unit: '44 g', brand: 'Knorr', discount: 8, deliveryTime: '10-20 mins' },
  { name: 'Saffola Masala Oats (400g)', category: 'Instant Food', price: 180, mrp: 200, unit: '400 g', brand: 'Saffola', discount: 10, deliveryTime: '10-20 mins' },
  { name: 'Amul Frozen Pizza (250g)', category: 'Instant Food', price: 120, mrp: 140, unit: '250 g', brand: 'Amul', discount: 14, deliveryTime: '20-30 mins' },
  { name: 'MTR Poha (160g)', category: 'Instant Food', price: 45, mrp: 50, unit: '160 g', brand: 'MTR', discount: 10, deliveryTime: '10-20 mins' },
  { name: 'ITC Master Chef Veg Burger Patties (400g)', category: 'Instant Food', price: 160, mrp: 180, unit: '400 g', brand: 'ITC Master Chef', discount: 11, deliveryTime: '20-30 mins' },
  { name: 'Maggi Pazzta Cheese Macaroni (70g)', category: 'Instant Food', price: 30, mrp: 35, unit: '70 g', brand: 'Maggi', discount: 14, deliveryTime: '10-20 mins' },

  // BEVERAGES
  { name: 'Pepsi Soft Drink (750ml)', category: 'Beverages', price: 40, mrp: 45, unit: '750 ml', brand: 'Pepsi', discount: 11, deliveryTime: '10-20 mins' },
  { name: 'Sprite Cold Drink (750ml)', category: 'Beverages', price: 40, mrp: 45, unit: '750 ml', brand: 'Sprite', discount: 11, deliveryTime: '10-20 mins' },
  { name: 'Red Bull Energy Drink (250ml)', category: 'Beverages', price: 115, mrp: 125, unit: '250 ml', brand: 'Red Bull', discount: 8, deliveryTime: '10-20 mins' },
  { name: 'Tropicana 100% Orange Juice (1L)', category: 'Beverages', price: 120, mrp: 135, unit: '1 L', brand: 'Tropicana', discount: 11, deliveryTime: '10-20 mins' },
  { name: 'Lipton Green Tea (25 bags)', category: 'Beverages', price: 140, mrp: 160, unit: '25 bags', brand: 'Lipton', discount: 12, deliveryTime: '10-20 mins' },
  { name: 'Monster Energy Drink (350ml)', category: 'Beverages', price: 110, mrp: 120, unit: '350 ml', brand: 'Monster', discount: 8, deliveryTime: '10-20 mins' },
  { name: 'Hershey\'s Flavored Milk (180ml)', category: 'Beverages', price: 35, mrp: 40, unit: '180 ml', brand: 'Hershey\'s', discount: 12, deliveryTime: '10-20 mins' },
  { name: 'Ensure High Protein Drink (400g)', category: 'Beverages', price: 680, mrp: 750, unit: '400 g', brand: 'Ensure', discount: 9, deliveryTime: '20-30 mins' },
  { name: 'Paper Boat Aamras (250ml)', category: 'Beverages', price: 30, mrp: 35, unit: '250 ml', brand: 'Paper Boat', discount: 14, deliveryTime: '10-20 mins' },
  { name: 'Nescafé Cold Coffee (180ml)', category: 'Beverages', price: 40, mrp: 45, unit: '180 ml', brand: 'Nescafé', discount: 11, deliveryTime: '10-20 mins' },

  // PERSONAL CARE
  { name: 'Head & Shoulders Shampoo (340ml)', category: 'Personal Care', price: 290, mrp: 320, unit: '340 ml', brand: 'Head & Shoulders', discount: 9, deliveryTime: '20-30 mins' },
  { name: 'Pears Pure & Gentle Soap (125g x 3)', category: 'Personal Care', price: 150, mrp: 175, unit: '3 pcs', brand: 'Pears', discount: 14, deliveryTime: '10-20 mins' },
  { name: 'Himalaya Purifying Neem Face Wash (150ml)', category: 'Personal Care', price: 160, mrp: 180, unit: '150 ml', brand: 'Himalaya', discount: 11, deliveryTime: '10-20 mins' },
  { name: 'Colgate Strong Teeth Toothpaste (200g)', category: 'Personal Care', price: 105, mrp: 120, unit: '200 g', brand: 'Colgate', discount: 12, deliveryTime: '10-20 mins' },
  { name: 'Oral-B CrossAction Toothbrush (3 pcs)', category: 'Personal Care', price: 140, mrp: 160, unit: '3 pcs', brand: 'Oral-B', discount: 12, deliveryTime: '10-20 mins' },
  { name: 'Vaseline Intensive Care Body Lotion (400ml)', category: 'Personal Care', price: 260, mrp: 300, unit: '400 ml', brand: 'Vaseline', discount: 13, deliveryTime: '20-30 mins' },
  { name: 'Nivea Men Deodorant (150ml)', category: 'Personal Care', price: 190, mrp: 220, unit: '150 ml', brand: 'Nivea', discount: 13, deliveryTime: '10-20 mins' },
  { name: 'Parachute Advanced Jasmine Hair Oil (300ml)', category: 'Personal Care', price: 140, mrp: 160, unit: '300 ml', brand: 'Parachute', discount: 12, deliveryTime: '10-20 mins' },
  { name: 'Savlon Hand Wash (750ml)', category: 'Personal Care', price: 115, mrp: 130, unit: '750 ml', brand: 'Savlon', discount: 11, deliveryTime: '10-20 mins' },
  { name: 'Lifebuoy Hand Sanitizer (50ml)', category: 'Personal Care', price: 25, mrp: 25, unit: '50 ml', brand: 'Lifebuoy', discount: 0, deliveryTime: '10-20 mins' },
];

const categoryColors = {
  'Staples': 'f5f5f5/333333',
  'Snacks': 'fff8e1/ff6f00',
  'Dairy': 'e3f2fd/1565c0',
  'Fruits & Veggies': 'e8f5e9/2e7d32',
  'Instant Food': 'ffebee/c62828',
  'Beverages': 'fce4ec/ad1457',
  'Personal Care': 'f3e5f5/6a1b9a'
};

const processedNewItems = newItemsData.map((item, index) => {
  const brandName = item.brand || 'Brand';
  const itemName = encodeURIComponent(item.name.split(' ').slice(0,2).join(' '));
  const color = categoryColors[item.category] || 'cccccc/000000';
  
  return {
    id: "g" + (21 + index),
    name: item.name,
    category: item.category,
    price: item.price,
    mrp: item.mrp,
    unit: item.unit,
    rating: (Math.random() * 1.5 + 3.5).toFixed(1),
    stock: Math.floor(Math.random() * 100) + 10,
    description: "Premium quality " + item.name + " by " + brandName,
    brand: item.brand,
    discount: item.discount,
    deliveryTime: item.deliveryTime,
    image: "https://placehold.co/400x400/" + color + "?text=" + itemName,
    inStock: true,
    bulkSaving: item.mrp - item.price,
    pooledOrders: Math.floor(Math.random() * 50) + 5,
  }
});

const enhancedOriginalItems = originalItems.map(item => ({
  ...item,
  rating: item.rating || (Math.random() * 1.5 + 3.5).toFixed(1),
  stock: item.stock || (item.inStock ? Math.floor(Math.random() * 100) + 10 : 0),
  description: item.description || ("High quality " + item.name),
  brand: item.brand || 'EliteMart Choice',
  discount: item.discount || (item.mrp && item.price ? Math.round(((item.mrp - item.price) / item.mrp) * 100) : 5),
  deliveryTime: item.deliveryTime || '15-30 mins',
}));

const finalItems = [...enhancedOriginalItems, ...processedNewItems];

const fileContent = "// groceryData.js — Mock grocery products for CampusMart module\\n" +
"export const groceryCategories = ['All', 'Staples', 'Snacks', 'Dairy', 'Fruits & Veggies', 'Instant Food', 'Beverages', 'Personal Care'];\\n\\n" +
"export const groceryItems = " + JSON.stringify(finalItems, null, 2) + ";\\n";

fs.writeFileSync(path.join(__dirname, '../src/data/groceryData.js'), fileContent);
console.log('Successfully expanded grocery data!');
